---
galaxy_info:
  company: 45Drives
  author: Brett Kelly
  description: Configures ccremer Znapzend Exporter
  license: Apache
  min_ansible_version: 2.4
  platforms:
    - name: EL
      versions:
        - 7
  galaxy_tags:
    - system
dependencies: []
